name: 'S35_WF_NAME <img src=x onerror=alert(1)>END'
on: workflow_dispatch
jobs:
  test:
    name: 'job_name "><svg/onload=alert(2)>'
    runs-on: ubuntu-latest
    steps:
      - name: 'step "><img onerror=alert(3) src=x>'
        run: echo hi
