name: Secret Leak PoC
on:
  workflow_dispatch:
env:
  MY_SECRET: ${{ secrets.TEST_SECRET_VALUE }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: volta-test-package.json
        continue-on-error: true
      - if: always()
        run: echo "done"
